# v1.0 syntax
version: '1.0'

services:
 
  tradepoint:
    image: sheerikie/tradepoint:latest
    ports:
      - "8080:8080" # real:container
    #networks:
      #- hnlnet
  # NodeJs 8
  tradepointUI:
    image: sheerikie/tradepoint:latest
    depends_on:
      - tradepoint
    ports:
      - "8081:8080" # real:container
    #networks:
      #- tradepointnet
#networks:
  #tradepointnet:
